use_frameworks!

target 'YMPodTestLib_Example' do
  pod 'YMPodTestLib', :path => '../'

  target 'YMPodTestLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
